// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: toplist.proto

#ifndef PROTOBUF_toplist_2eproto__INCLUDED
#define PROTOBUF_toplist_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_toplist_2eproto();
void protobuf_AssignDesc_toplist_2eproto();
void protobuf_ShutdownFile_toplist_2eproto();

class Toplist;

// ===================================================================

class Toplist : public ::google::protobuf::Message {
 public:
  Toplist();
  virtual ~Toplist();

  Toplist(const Toplist& from);

  inline Toplist& operator=(const Toplist& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Toplist& default_instance();

  void Swap(Toplist* other);

  // implements Message ----------------------------------------------

  Toplist* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Toplist& from);
  void MergeFrom(const Toplist& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string items = 1;
  inline int items_size() const;
  inline void clear_items();
  static const int kItemsFieldNumber = 1;
  inline const ::std::string& items(int index) const;
  inline ::std::string* mutable_items(int index);
  inline void set_items(int index, const ::std::string& value);
  inline void set_items(int index, const char* value);
  inline void set_items(int index, const char* value, size_t size);
  inline ::std::string* add_items();
  inline void add_items(const ::std::string& value);
  inline void add_items(const char* value);
  inline void add_items(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& items() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_items();

  // @@protoc_insertion_point(class_scope:Toplist)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> items_;
  friend void  protobuf_AddDesc_toplist_2eproto();
  friend void protobuf_AssignDesc_toplist_2eproto();
  friend void protobuf_ShutdownFile_toplist_2eproto();

  void InitAsDefaultInstance();
  static Toplist* default_instance_;
};
// ===================================================================


// ===================================================================

// Toplist

// repeated string items = 1;
inline int Toplist::items_size() const {
  return items_.size();
}
inline void Toplist::clear_items() {
  items_.Clear();
}
inline const ::std::string& Toplist::items(int index) const {
  // @@protoc_insertion_point(field_get:Toplist.items)
  return items_.Get(index);
}
inline ::std::string* Toplist::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:Toplist.items)
  return items_.Mutable(index);
}
inline void Toplist::set_items(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Toplist.items)
  items_.Mutable(index)->assign(value);
}
inline void Toplist::set_items(int index, const char* value) {
  items_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:Toplist.items)
}
inline void Toplist::set_items(int index, const char* value, size_t size) {
  items_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Toplist.items)
}
inline ::std::string* Toplist::add_items() {
  return items_.Add();
}
inline void Toplist::add_items(const ::std::string& value) {
  items_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:Toplist.items)
}
inline void Toplist::add_items(const char* value) {
  items_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:Toplist.items)
}
inline void Toplist::add_items(const char* value, size_t size) {
  items_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:Toplist.items)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Toplist::items() const {
  // @@protoc_insertion_point(field_list:Toplist.items)
  return items_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Toplist::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:Toplist.items)
  return &items_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_toplist_2eproto__INCLUDED
